import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar.jsx'
import Vaults from "../components/vaults"
import Landing from "../components/Landing"
import web2 from 'web3'
import React, { useState } from 'react'
import Link from 'next/link.js'

async function handleClick() {
  console.log('clicked')
}


export default function Home({ WETH_VAULT }) {
  return (
    <div>
      <Head>
        <title>Mai Liquidatooor</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>
        {/*<Vaults vaults={WETH_VAULT} />*/}
       {<Landing/>}
      </div>
    </div>

  )
}